### PR TITLE
Added Switch Row UI type

### PR DESCRIPTION
**Pull request by emms007**
Hello,

Just added friendly UI control for multiple icon "switches" inline.

This is basically the blending of "button row" that allows multiple controls on one line, plus the switch On/Off functionalities allowing external values to update them. Icon coloration is used to display state.

Regards,
Emms007

### CODE REVIEW

**Comment by emms007** [comment]
Actual demo:
image

**Comment by andrei-tatar** [comment]
Have you tested this? I can't seem to get it working ok. 
Refreshing the page does not keep the state of the buttons. 
Sending a message to the input does not seem to update the button status. Maybe I'm not doing it right. 
Also, the code seems overly complicated.

I showed an example of how to do this using a template node, with the following template:
```html
<div flex layout="row" layout-align="space-around center">
    <md-button ng-repeat="b in buttons" class="md-icon-button" ng-click="click(b)">
        <ng-md-icon icon="{{msg.payload[b.payload]?b.icon2:b.icon}}"
                    ng-style="{color: msg.payload[b.payload]?b.color2:b.color}"></ng-md-icon>
    </md-button>
</div>

<script>
    scope.buttons = [{
        icon: 'pause', color: 'black',
        icon2: 'play_arrow', color2: 'red',
        payload: 'play',
    }, {
        icon: 'alarm', color: 'black',
        icon2: 'alarm', color2: 'red',
        payload: 'alarm',
    }];
    
    scope.click = function(b) {
        if (!this.msg) this.msg = {};
        if (!this.msg.payload) this.msg.payload = {};
        this.msg.payload[b.payload] = !this.msg.payload[b.payload];
        this.send(this.msg);
    }.bind(scope);
</script>
```

I think I will expand the existing button_row to support toggling the buttons.

**Comment by emms007** [comment]
Good to see a simpler way, sounds very good to do it on the page itself merged with current button_row.

The one I suggested indeed works for toggling, but the initial state after refresh is a bit awkward. In my mqtt setup I get regular updates of the state of buttons and never refresh so it is invisible.

From my understanding your demo only deals about sending an output value, while the complexity I had was rather about processing the input. Especially in the context where one inbound message will change the value of only one button, keeping the rest unchanged.

**Comment by andrei-tatar** [comment]
Yes, that example needs the entire state on the input but it can easily be changed so that it can handle single values.

**Pull request closed without merging**
